export const Cryptos = [
    //TDQAIZJI7RJ67E14WZG492KHII9NIJCXX4
    {
        id: 'USDT-TRC20',
        name: 'USDT',
        network: 'TRC20',
        chain: 'Tron',
        symbol: 'USDT',
        baseId: 'USDT',
        address: 'TDazU2DipEUuc9KjRE4A5STAxees4vQQd1',
        confirmTime: 180,
        icon: '/icons/usdt.svg',
        networkIcon: '/icons/trx.svg',
    },

    {
        id: 'USDT-BEP20',
        name: 'USDT',
        network: 'BEP20',
        chain: 'BNB Smart Chain',
        symbol: 'USDT',
        baseId: 'USDT',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 90,
        icon: '/icons/usdt.svg',
        networkIcon: '/icons/bnb.svg',
    },

    {
        id: 'USDT-ERC20',
        name: 'USDT',
        network: 'ERC20',
        chain: 'Ethereum',
        symbol: 'USDT',
        baseId: 'USDT',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 300,
        icon: '/icons/usdt.svg',
        networkIcon: '/icons/eth.svg',
    },

    {
        id: 'USDC-ERC20',
        name: 'USDC',
        network: 'ERC20',
        chain: 'Ethereum',
        symbol: 'USDC',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 300,
        icon: '/icons/usdc.svg',
        networkIcon: '/icons/eth.svg',
    },

    {
        id: 'USDC-BEP20',
        name: 'USDC',
        network: 'BEP20',
        chain: 'BNB Smart Chain',
        symbol: 'USDC',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 300,
        icon: '/icons/usdc.svg',
        networkIcon: '/icons/bnb.svg',
    },

    {
        id: 'USDC-TRC20',
        name: 'USDC',
        network: 'TRC20',
        chain: 'Tron',
        symbol: 'USDC',
        address: 'TDazU2DipEUuc9KjRE4A5STAxees4vQQd1',
        confirmTime: 300,
        icon: '/icons/usdc.svg',
        networkIcon: '/icons/trx.svg',
    },

    {
        id: 'BTC',
        name: 'Bitcoin',
        network: 'BTC',
        chain: 'Bitcoin',
        symbol: '₿',
        address: 'bc1q7tcdp9535hy6xkgn9rxrvjfh6xn49qe8dfrejf',
        confirmTime: 900,
        url: 'https://api.blockcypher.com/v1/btc/main/addrs/bc1q7tcdp9535hy6xkgn9rxrvjfh6xn49qe8dfrejf/full',
        icon: '/icons/btc.svg',
        networkIcon: '/icons/btc.svg',
    },
    {
        id: 'ETH',
        name: 'Ethereum',
        network: 'ETH',
        chain: 'Ethereum',
        symbol: 'Ξ',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 300,
        icon: '/icons/eth.svg',
        networkIcon: '/icons/eth.svg',
    },

    {
        id: 'TON',
        name: 'TON',
        network: 'TON',
        chain: 'The Open Network',
        symbol: 'TON',
        address: 'UQBiSXZ5Gl2FOwZjaicynNitbfI_qFRfvwsyl21Z3L6W7Jp4',
        confirmTime: 120,
        icon: '/icons/ton.svg',
        networkIcon: '/icons/ton.svg',
    },

    {
        id: 'WMATIC',
        name: 'WMATIC',
        network: 'Polygon',
        chain: 'Polygon',
        symbol: 'MATIC',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 120,
        icon: '/icons/wmatic.svg',
        networkIcon: '/icons/wmatic.svg',
    },

    {
        id: 'ARB',
        name: 'ARB',
        network: 'Arbitrum',
        chain: 'Arbitrum One',
        symbol: 'ARB',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 180,
        icon: '/icons/arb.svg',
        networkIcon: '/icons/arb.svg',
    },

    {
        id: 'OP',
        name: 'OP',
        network: 'Optimism',
        chain: 'Optimism',
        symbol: 'OP',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 180,
        icon: '/icons/op.svg',
        networkIcon: '/icons/op.svg',
    },

    {
        id: 'AVAX',
        name: 'AVAX',
        network: 'Avalanche',
        chain: 'Avalanche C-Chain',
        symbol: 'AVAX',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 120,
        icon: '/icons/avax.svg',
        networkIcon: '/icons/avax.svg',
    },

    {
        id: 'BNB',
        name: 'BNB',
        network: 'BEP20',
        chain: 'BNB Smart Chain',
        symbol: 'BNB',
        address: '0xe50850cA86b0Dd7fcB8fa9977df611d19B517fC6',
        confirmTime: 90,
        icon: '/icons/bnb.svg',
        networkIcon: '/icons/bnb.svg',
    },

    {
        id: 'TRX',
        name: 'TRX',
        network: 'Tron',
        chain: 'Tron',
        symbol: 'TRX',
        address: 'TDazU2DipEUuc9KjRE4A5STAxees4vQQd1',
        confirmTime: 180,
        icon: '/icons/trx.svg',
        networkIcon: '/icons/trx.svg',
    },

    {
        id: 'SOL',
        name: 'SOL',
        network: 'Solana',
        chain: 'Solana',
        symbol: 'SOL',
        address: 'EdgKkmnhnfNvguJ6gBe29L5rB81hcQWJWbpNtjM5ncGH',
        confirmTime: 60,
        icon: '/icons/sol.svg',
        networkIcon: '/icons/sol.svg',
    },
];
