export { default as FooterPage } from '../list/Pagination';
export { default as Action } from './Action';
export { default as Card } from './Card';
export { default as Col } from './Col';
export { default as Content } from './Content';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Page } from './Page';
export { default as Row } from './Row';
