// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateImages = `-- name: BatchCreateImages :batchexec
INSERT INTO images (
    storage_path,
    file_name,
    file_type,
    mime_type,
    height_px,
    width_px
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type BatchCreateImagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateImagesParams struct {
	StoragePath string `json:"storage_path"`
	FileName    string `json:"file_name"`
	FileType    string `json:"file_type"`
	MimeType    string `json:"mime_type"`
	HeightPx    int32  `json:"height_px"`
	WidthPx     int32  `json:"width_px"`
}

func (q *Queries) BatchCreateImages(ctx context.Context, arg []BatchCreateImagesParams) *BatchCreateImagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.StoragePath,
			a.FileName,
			a.FileType,
			a.MimeType,
			a.HeightPx,
			a.WidthPx,
		}
		batch.Queue(batchCreateImages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateImagesBatchResults{br, len(arg), false}
}

func (b *BatchCreateImagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateImagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchCreateProductSkus = `-- name: BatchCreateProductSkus :batchexec
INSERT INTO product_skus (
    product_id,
    title,
    code,
    image,
    price,
    stock,
    weight_g,
    status,
    stored,
    ukey,
    akey,
    attrs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type BatchCreateProductSkusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateProductSkusParams struct {
	ProductID int64        `json:"product_id"`
	Title     string       `json:"title"`
	Code      string       `json:"code"`
	Image     string       `json:"image"`
	Price     int64        `json:"price"`
	Stock     int32        `json:"stock"`
	WeightG   int32        `json:"weight_g"`
	Status    int16        `json:"status"`
	Stored    int16        `json:"stored"`
	Ukey      string       `json:"ukey"`
	Akey      string       `json:"akey"`
	Attrs     dbtypes.JSON `json:"attrs"`
}

func (q *Queries) BatchCreateProductSkus(ctx context.Context, arg []BatchCreateProductSkusParams) *BatchCreateProductSkusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProductID,
			a.Title,
			a.Code,
			a.Image,
			a.Price,
			a.Stock,
			a.WeightG,
			a.Status,
			a.Stored,
			a.Ukey,
			a.Akey,
			a.Attrs,
		}
		batch.Queue(batchCreateProductSkus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateProductSkusBatchResults{br, len(arg), false}
}

func (b *BatchCreateProductSkusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateProductSkusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpdateProductSkus = `-- name: BatchUpdateProductSkus :batchexec
UPDATE product_skus
SET
    title      = $1,
    code       = $2,
    image      = $3,
    price      = $4,
    stock      = $5,
    weight_g   = $6,
    status     = $7,
    uts        = $8 
WHERE product_id = $9 AND id = $10
`

type BatchUpdateProductSkusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpdateProductSkusParams struct {
	Title     string      `json:"title"`
	Code      string      `json:"code"`
	Image     string      `json:"image"`
	Price     int64       `json:"price"`
	Stock     int32       `json:"stock"`
	WeightG   int32       `json:"weight_g"`
	Status    int16       `json:"status"`
	Uts       pgtype.Int8 `json:"uts"`
	ProductID int64       `json:"product_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) BatchUpdateProductSkus(ctx context.Context, arg []BatchUpdateProductSkusParams) *BatchUpdateProductSkusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Title,
			a.Code,
			a.Image,
			a.Price,
			a.Stock,
			a.WeightG,
			a.Status,
			a.Uts,
			a.ProductID,
			a.ID,
		}
		batch.Queue(batchUpdateProductSkus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpdateProductSkusBatchResults{br, len(arg), false}
}

func (b *BatchUpdateProductSkusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpdateProductSkusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
