// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateProductSku = `-- name: BatchCreateProductSku :batchexec
INSERT INTO product_skus (
    product_id,
    name,
    image,
    price,
    stock,
    weight_g,
    attrs,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type BatchCreateProductSkuBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateProductSkuParams struct {
	ProductID int64          `json:"product_id"`
	Name      string         `json:"name"`
	Image     string         `json:"image"`
	Price     pgtype.Numeric `json:"price"`
	Stock     int32          `json:"stock"`
	WeightG   int32          `json:"weight_g"`
	Attrs     dbtypes.JSON   `json:"attrs"`
	Status    int16          `json:"status"`
}

func (q *Queries) BatchCreateProductSku(ctx context.Context, arg []BatchCreateProductSkuParams) *BatchCreateProductSkuBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProductID,
			a.Name,
			a.Image,
			a.Price,
			a.Stock,
			a.WeightG,
			a.Attrs,
			a.Status,
		}
		batch.Queue(batchCreateProductSku, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateProductSkuBatchResults{br, len(arg), false}
}

func (b *BatchCreateProductSkuBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateProductSkuBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchDeleteProducts = `-- name: BatchDeleteProducts :batchexec
DELETE FROM products WHERE id = $1
`

type BatchDeleteProductsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) BatchDeleteProducts(ctx context.Context, id []int64) *BatchDeleteProductsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchDeleteProducts, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchDeleteProductsBatchResults{br, len(id), false}
}

func (b *BatchDeleteProductsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchDeleteProductsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
