// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baseImageCountSql = `-- name: BaseImageCountSql :one
SELECT COUNT(*) FROM images
`

func (q *Queries) BaseImageCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseImageCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseImageListSql = `-- name: BaseImageListSql :many
SELECT 
    id,
    CASE 
        WHEN url = '' THEN file_name  ELSE url 
    END AS url,
    storage_path,
    file_name,
    file_type,
    mime_type,
    alt_text,
    width_px,
    height_px,
    cts
FROM images
`

type BaseImageListSqlRow struct {
	ID          int64       `json:"id"`
	Url         interface{} `json:"url"`
	StoragePath string      `json:"storage_path"`
	FileName    string      `json:"file_name"`
	FileType    string      `json:"file_type"`
	MimeType    string      `json:"mime_type"`
	AltText     string      `json:"alt_text"`
	WidthPx     int32       `json:"width_px"`
	HeightPx    int32       `json:"height_px"`
	Cts         pgtype.Int8 `json:"cts"`
}

func (q *Queries) BaseImageListSql(ctx context.Context) ([]BaseImageListSqlRow, error) {
	rows, err := q.db.Query(ctx, baseImageListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseImageListSqlRow
	for rows.Next() {
		var i BaseImageListSqlRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.StoragePath,
			&i.FileName,
			&i.FileType,
			&i.MimeType,
			&i.AltText,
			&i.WidthPx,
			&i.HeightPx,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchDeleteImages = `-- name: BatchDeleteImages :exec
DELETE FROM images WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteImages(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteImages, ids)
	return err
}

const getImagesByNames = `-- name: GetImagesByNames :many
SELECT file_name FROM images WHERE file_name = ANY($1::text[])
`

func (q *Queries) GetImagesByNames(ctx context.Context, fileNames []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getImagesByNames, fileNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_name string
		if err := rows.Scan(&file_name); err != nil {
			return nil, err
		}
		items = append(items, file_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, url, storage_path, file_name, file_type, mime_type, alt_text, width_px, height_px, size, platform, cts FROM images
ORDER BY cts DESC
LIMIT $1 OFFSET $2
`

type ListImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.StoragePath,
			&i.FileName,
			&i.FileType,
			&i.MimeType,
			&i.AltText,
			&i.WidthPx,
			&i.HeightPx,
			&i.Size,
			&i.Platform,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
