// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const baseLogsCountSql = `-- name: BaseLogsCountSql :one
SELECT count(*) FROM logs
`

func (q *Queries) BaseLogsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseLogsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseLogsListSql = `-- name: BaseLogsListSql :many
SELECT id, sid, ukey, domain, source, ts, fps, ips, cts FROM logs
`

func (q *Queries) BaseLogsListSql(ctx context.Context) ([]Log, error) {
	rows, err := q.db.Query(ctx, baseLogsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Sid,
			&i.Ukey,
			&i.Domain,
			&i.Source,
			&i.Ts,
			&i.Fps,
			&i.Ips,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLogs = `-- name: CreateLogs :exec
INSERT INTO logs (
    sid,
    ukey,   
    source,
    ts,
    domain,
    fps,
    ips
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLogsParams struct {
	Sid    int64        `json:"sid"`
	Ukey   string       `json:"ukey"`
	Source string       `json:"source"`
	Ts     int64        `json:"ts"`
	Domain string       `json:"domain"`
	Fps    dbtypes.JSON `json:"fps"`
	Ips    dbtypes.JSON `json:"ips"`
}

func (q *Queries) CreateLogs(ctx context.Context, arg CreateLogsParams) error {
	_, err := q.db.Exec(ctx, createLogs,
		arg.Sid,
		arg.Ukey,
		arg.Source,
		arg.Ts,
		arg.Domain,
		arg.Fps,
		arg.Ips,
	)
	return err
}
