// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const createLog = `-- name: CreateLog :exec
INSERT INTO logs (
    ukey,
    source,
    ts,
    fps,
    ips
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLogParams struct {
	Ukey   string       `json:"ukey"`
	Source string       `json:"source"`
	Ts     int64        `json:"ts"`
	Fps    dbtypes.JSON `json:"fps"`
	Ips    dbtypes.JSON `json:"ips"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.Exec(ctx, createLog,
		arg.Ukey,
		arg.Source,
		arg.Ts,
		arg.Fps,
		arg.Ips,
	)
	return err
}
