// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID       int32       `json:"id"`
	Filename string      `json:"filename"`
	Itype    string      `json:"itype"`
	MimeType string      `json:"mime_type"`
	AltText  pgtype.Text `json:"alt_text"`
	Width    pgtype.Int4 `json:"width"`
	Height   pgtype.Int4 `json:"height"`
	Cts      pgtype.Int8 `json:"cts"`
}

type Product struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Handle       string         `json:"handle"`
	Tags         []string       `json:"tags"`
	Status       pgtype.Int2    `json:"status"`
	Deleted      pgtype.Int2    `json:"deleted"`
	WeightG      pgtype.Int4    `json:"weight_g"`
	Brand        pgtype.Text    `json:"brand"`
	Category     pgtype.Text    `json:"category"`
	MainImageUrl pgtype.Text    `json:"main_image_url"`
	SalesCount   pgtype.Int4    `json:"sales_count"`
	Price        pgtype.Numeric `json:"price"`
	Cts          pgtype.Int8    `json:"cts"`
	Uts          pgtype.Int8    `json:"uts"`
}

type ProductContent struct {
	ProductID int64       `json:"product_id"`
	Content   pgtype.Text `json:"content"`
}

type ProductDetail struct {
	ProductID int64         `json:"product_id"`
	Images    []string      `json:"images"`
	Videos    *dbtypes.JSON `json:"videos"`
	Specs     *dbtypes.JSON `json:"specs"`
	Cts       pgtype.Int8   `json:"cts"`
	Uts       pgtype.Int8   `json:"uts"`
}

type ProductMetum struct {
	ProductID       int64       `json:"product_id"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	Keywords        pgtype.Text `json:"keywords"`
	IsFeatured      pgtype.Bool `json:"is_featured"`
	SortPriority    pgtype.Int4 `json:"sort_priority"`
	ShowInSlider    pgtype.Bool `json:"show_in_slider"`
	WarrantyMonths  pgtype.Int4 `json:"warranty_months"`
	OriginCountry   pgtype.Text `json:"origin_country"`
	WeightG         pgtype.Int4 `json:"weight_g"`
	Material        pgtype.Text `json:"material"`
	ShopifyID       pgtype.Text `json:"shopify_id"`
	GoogleCategory  pgtype.Text `json:"google_category"`
	Cts             pgtype.Int8 `json:"cts"`
	Uts             pgtype.Int8 `json:"uts"`
}

type ProductOption struct {
	ProductID int64        `json:"product_id"`
	Options   dbtypes.JSON `json:"options"`
	Cts       pgtype.Int8  `json:"cts"`
	Uts       pgtype.Int8  `json:"uts"`
}

type ProductSku struct {
	ID        string         `json:"id"`
	ProductID int64          `json:"product_id"`
	Img       pgtype.Text    `json:"img"`
	Price     pgtype.Numeric `json:"price"`
	Stock     int32          `json:"stock"`
	WeightG   pgtype.Int4    `json:"weight_g"`
	Attrs     dbtypes.JSON   `json:"attrs"`
	Status    pgtype.Int2    `json:"status"`
	Cts       pgtype.Int8    `json:"cts"`
	Uts       pgtype.Int8    `json:"uts"`
}
