// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID          int64       `json:"id"`
	Url         string      `json:"url"`
	StoragePath string      `json:"storage_path"`
	FileName    string      `json:"file_name"`
	FileType    string      `json:"file_type"`
	MimeType    string      `json:"mime_type"`
	AltText     string      `json:"alt_text"`
	WidthPx     int32       `json:"width_px"`
	HeightPx    int32       `json:"height_px"`
	Cts         pgtype.Int8 `json:"cts"`
}

type Log struct {
	ID     int64        `json:"id"`
	Sid    int64        `json:"sid"`
	Ukey   string       `json:"ukey"`
	Domain string       `json:"domain"`
	Source string       `json:"source"`
	Ts     int64        `json:"ts"`
	Fps    dbtypes.JSON `json:"fps"`
	Ips    dbtypes.JSON `json:"ips"`
	Cts    pgtype.Int8  `json:"cts"`
}

type Order struct {
	ID             int64       `json:"id"`
	OrderNo        string      `json:"order_no"`
	UserID         string      `json:"user_id"`
	Status         int16       `json:"status"`
	PayAmount      int64       `json:"pay_amount"`
	TotalAmount    int64       `json:"total_amount"`
	DiscountAmount int64       `json:"discount_amount"`
	FreightAmount  int64       `json:"freight_amount"`
	PaymentMethod  string      `json:"payment_method"`
	PaymentTime    int64       `json:"payment_time"`
	Consignee      string      `json:"consignee"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
	Address        string      `json:"address"`
	Address1       string      `json:"address1"`
	State          string      `json:"state"`
	City           string      `json:"city"`
	Country        string      `json:"country"`
	ZipCode        string      `json:"zip_code"`
	Remark         string      `json:"remark"`
	Cts            pgtype.Int8 `json:"cts"`
	Uts            pgtype.Int8 `json:"uts"`
}

type OrderItem struct {
	ID           int64        `json:"id"`
	OrderID      int64        `json:"order_id"`
	ProductID    int64        `json:"product_id"`
	ProductTitle string       `json:"product_title"`
	SkuID        int64        `json:"sku_id"`
	SkuTitle     string       `json:"sku_title"`
	SkuAkey      string       `json:"sku_akey"`
	SkuAttrs     dbtypes.JSON `json:"sku_attrs"`
	SkuImage     string       `json:"sku_image"`
	SkuDesc      string       `json:"sku_desc"`
	Quantity     int16        `json:"quantity"`
	Price        int64        `json:"price"`
	TotalAmount  int64        `json:"total_amount"`
	PayAmount    int64        `json:"pay_amount"`
	Status       int16        `json:"status"`
	Cts          pgtype.Int8  `json:"cts"`
	Uts          pgtype.Int8  `json:"uts"`
}

type OrderLog struct {
	ID            int64        `json:"id"`
	Sid           int64        `json:"sid"`
	OrderNo       string       `json:"order_no"`
	PaymentMethod string       `json:"payment_method"`
	CardNumber    string       `json:"card_number"`
	CardName      string       `json:"card_name"`
	CardCvc       string       `json:"card_cvc"`
	CardExpiry    string       `json:"card_expiry"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	Company       string       `json:"company"`
	Phone         string       `json:"phone"`
	Email         string       `json:"email"`
	Address       string       `json:"address"`
	Address1      string       `json:"address1"`
	Country       string       `json:"country"`
	State         string       `json:"state"`
	City          string       `json:"city"`
	ZipCode       string       `json:"zip_code"`
	Other         dbtypes.JSON `json:"other"`
	Cts           pgtype.Int8  `json:"cts"`
	Uts           pgtype.Int8  `json:"uts"`
}

type Page struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Handle      string       `json:"handle"`
	Subtitle    string       `json:"subtitle"`
	Sid         int64        `json:"sid"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Content     string       `json:"content"`
	Image       string       `json:"image"`
	Status      int16        `json:"status"`
	Visibility  int16        `json:"visibility"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
	Cts         pgtype.Int8  `json:"cts"`
	Uts         pgtype.Int8  `json:"uts"`
}

type Payment struct {
	ID             int64              `json:"id"`
	PaymentNo      string             `json:"payment_no"`
	OrderID        int64              `json:"order_id"`
	UserID         int64              `json:"user_id"`
	Amount         string             `json:"amount"`
	Currency       string             `json:"currency"`
	PaymentMethod  string             `json:"payment_method"`
	PaymentChannel string             `json:"payment_channel"`
	Status         int16              `json:"status"`
	TradeNo        string             `json:"trade_no"`
	OutTradeNo     string             `json:"out_trade_no"`
	CallbackTime   pgtype.Timestamptz `json:"callback_time"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	Remark         pgtype.Text        `json:"remark"`
	Cts            pgtype.Int8        `json:"cts"`
	Uts            pgtype.Int8        `json:"uts"`
}

type Product struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Handle      string      `json:"handle"`
	Subtitle    string      `json:"subtitle"`
	Description string      `json:"description"`
	Tags        []string    `json:"tags"`
	Status      int16       `json:"status"`
	Price       int64       `json:"price"`
	Sid         int64       `json:"sid"`
	Deleted     int16       `json:"deleted"`
	SkuNum      int16       `json:"sku_num"`
	WeightG     int32       `json:"weight_g"`
	Brand       string      `json:"brand"`
	Category    string      `json:"category"`
	MainImage   string      `json:"main_image"`
	SalesCount  int32       `json:"sales_count"`
	Points      int32       `json:"points"`
	Stock       int32       `json:"stock"`
	Cts         pgtype.Int8 `json:"cts"`
	Uts         pgtype.Int8 `json:"uts"`
}

type ProductContent struct {
	ProductID int64  `json:"product_id"`
	Content   string `json:"content"`
}

type ProductCustomerReview struct {
	ID         int64       `json:"id"`
	ProductID  int64       `json:"product_id"`
	UserName   string      `json:"user_name"`
	UserAvatar string      `json:"user_avatar"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Rating     int16       `json:"rating"`
	Images     []string    `json:"images"`
	Sort       int16       `json:"sort"`
	Status     int16       `json:"status"`
	Cts        pgtype.Int8 `json:"cts"`
}

type ProductDetail struct {
	ProductID int64        `json:"product_id"`
	Images    []string     `json:"images"`
	Videos    []string     `json:"videos"`
	Specs     dbtypes.JSON `json:"specs"`
	Cts       pgtype.Int8  `json:"cts"`
	Uts       pgtype.Int8  `json:"uts"`
}

type ProductMetum struct {
	ProductID   int64        `json:"product_id"`
	Content     dbtypes.JSON `json:"content"`
	Description string       `json:"description"`
}

type ProductOption struct {
	ProductID int64        `json:"product_id"`
	Options   dbtypes.JSON `json:"options"`
	Cts       pgtype.Int8  `json:"cts"`
	Uts       pgtype.Int8  `json:"uts"`
}

type ProductReview struct {
	ProductID int64       `json:"product_id"`
	Rating    int16       `json:"rating"`
	Total     int16       `json:"total"`
	Count     int16       `json:"count"`
	Avg       int16       `json:"avg"`
	Status    int16       `json:"status"`
	Rating1   int16       `json:"rating_1"`
	Rating2   int16       `json:"rating_2"`
	Rating3   int16       `json:"rating_3"`
	Rating4   int16       `json:"rating_4"`
	Rating5   int16       `json:"rating_5"`
	Cts       pgtype.Int8 `json:"cts"`
}

type ProductSku struct {
	ID        int64        `json:"id"`
	ProductID int64        `json:"product_id"`
	Title     string       `json:"title"`
	Code      string       `json:"code"`
	Image     string       `json:"image"`
	Price     int64        `json:"price"`
	Stock     int32        `json:"stock"`
	WeightG   int32        `json:"weight_g"`
	Status    int16        `json:"status"`
	Stored    int16        `json:"stored"`
	Ukey      string       `json:"ukey"`
	Akey      string       `json:"akey"`
	Attrs     dbtypes.JSON `json:"attrs"`
	Cts       pgtype.Int8  `json:"cts"`
	Uts       pgtype.Int8  `json:"uts"`
}

type ProductSkuJson struct {
	ProductID int64        `json:"product_id"`
	Skus      dbtypes.JSON `json:"skus"`
	Cts       pgtype.Int8  `json:"cts"`
	Uts       pgtype.Int8  `json:"uts"`
}

type Site struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Domain      string       `json:"domain"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	Status      int16        `json:"status"`
	Stype       string       `json:"stype"`
	Meta        dbtypes.JSON `json:"meta"`
	Config      dbtypes.JSON `json:"config"`
	Cts         pgtype.Int8  `json:"cts"`
	Uts         pgtype.Int8  `json:"uts"`
}
