// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_logs.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const baseOrderLogsCountSql = `-- name: BaseOrderLogsCountSql :one
SELECT count(*) FROM order_logs
`

func (q *Queries) BaseOrderLogsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseOrderLogsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseOrderLogsListSql = `-- name: BaseOrderLogsListSql :many
SELECT id, sid, order_no, payment_method, card_number, card_name, card_cvc, card_expiry, first_name, last_name, company, phone, email, address, address1, country, state, city, zip_code, other, cts, uts FROM order_logs
`

func (q *Queries) BaseOrderLogsListSql(ctx context.Context) ([]OrderLog, error) {
	rows, err := q.db.Query(ctx, baseOrderLogsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderLog
	for rows.Next() {
		var i OrderLog
		if err := rows.Scan(
			&i.ID,
			&i.Sid,
			&i.OrderNo,
			&i.PaymentMethod,
			&i.CardNumber,
			&i.CardName,
			&i.CardCvc,
			&i.CardExpiry,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Address1,
			&i.Country,
			&i.State,
			&i.City,
			&i.ZipCode,
			&i.Other,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrderLogs = `-- name: CreateOrderLogs :exec
INSERT INTO order_logs (
    sid,
    order_no,
    payment_method,
    card_number,
    card_name,
    card_cvc,
    card_expiry,
    first_name,
    last_name,
    company,
    phone,
    email,
    address,
    address1,
    country,
    state,
    city,
    zip_code,
    other
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
`

type CreateOrderLogsParams struct {
	Sid           int64        `json:"sid"`
	OrderNo       string       `json:"order_no"`
	PaymentMethod string       `json:"payment_method"`
	CardNumber    string       `json:"card_number"`
	CardName      string       `json:"card_name"`
	CardCvc       string       `json:"card_cvc"`
	CardExpiry    string       `json:"card_expiry"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	Company       string       `json:"company"`
	Phone         string       `json:"phone"`
	Email         string       `json:"email"`
	Address       string       `json:"address"`
	Address1      string       `json:"address1"`
	Country       string       `json:"country"`
	State         string       `json:"state"`
	City          string       `json:"city"`
	ZipCode       string       `json:"zip_code"`
	Other         dbtypes.JSON `json:"other"`
}

func (q *Queries) CreateOrderLogs(ctx context.Context, arg CreateOrderLogsParams) error {
	_, err := q.db.Exec(ctx, createOrderLogs,
		arg.Sid,
		arg.OrderNo,
		arg.PaymentMethod,
		arg.CardNumber,
		arg.CardName,
		arg.CardCvc,
		arg.CardExpiry,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Address1,
		arg.Country,
		arg.State,
		arg.City,
		arg.ZipCode,
		arg.Other,
	)
	return err
}

const deleteOrderLog = `-- name: DeleteOrderLog :exec
DELETE FROM order_logs WHERE id = $1
`

func (q *Queries) DeleteOrderLog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrderLog, id)
	return err
}
