// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5/pgtype"
)

const basePageCountSql = `-- name: BasePageCountSql :one
SELECT COUNT(*) FROM pages
`

func (q *Queries) BasePageCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, basePageCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const basePageListSql = `-- name: BasePageListSql :many
SELECT id, title, handle, subtitle, sid, description, stype, image, status, visibility, seo, meta,cts FROM pages
`

type BasePageListSqlRow struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Handle      string       `json:"handle"`
	Subtitle    string       `json:"subtitle"`
	Sid         int64        `json:"sid"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Image       string       `json:"image"`
	Status      int16        `json:"status"`
	Visibility  int16        `json:"visibility"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
	Cts         pgtype.Int8  `json:"cts"`
}

func (q *Queries) BasePageListSql(ctx context.Context) ([]BasePageListSqlRow, error) {
	rows, err := q.db.Query(ctx, basePageListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BasePageListSqlRow
	for rows.Next() {
		var i BasePageListSqlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Sid,
			&i.Description,
			&i.Stype,
			&i.Image,
			&i.Status,
			&i.Visibility,
			&i.Seo,
			&i.Meta,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchDeletePages = `-- name: BatchDeletePages :exec
DELETE FROM pages WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeletePages(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeletePages, ids)
	return err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (
    id, title, handle, subtitle, description, stype, content, image, seo, meta, visibility
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11    
)
`

type CreatePageParams struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Handle      string       `json:"handle"`
	Subtitle    string       `json:"subtitle"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Content     string       `json:"content"`
	Image       string       `json:"image"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
	Visibility  int16        `json:"visibility"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.Exec(ctx, createPage,
		arg.ID,
		arg.Title,
		arg.Handle,
		arg.Subtitle,
		arg.Description,
		arg.Stype,
		arg.Content,
		arg.Image,
		arg.Seo,
		arg.Meta,
		arg.Visibility,
	)
	return err
}

const fetchPage = `-- name: FetchPage :one
SELECT title, handle, subtitle, description, content, image, seo, meta 
FROM pages WHERE sid IN (0, $2) AND status=0 AND visibility=0 AND id = $1
`

type FetchPageParams struct {
	ID  int64 `json:"id"`
	Sid int64 `json:"sid"`
}

type FetchPageRow struct {
	Title       string       `json:"title"`
	Handle      string       `json:"handle"`
	Subtitle    string       `json:"subtitle"`
	Description string       `json:"description"`
	Content     string       `json:"content"`
	Image       string       `json:"image"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
}

func (q *Queries) FetchPage(ctx context.Context, arg FetchPageParams) (FetchPageRow, error) {
	row := q.db.QueryRow(ctx, fetchPage, arg.ID, arg.Sid)
	var i FetchPageRow
	err := row.Scan(
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Content,
		&i.Image,
		&i.Seo,
		&i.Meta,
	)
	return i, err
}

const getPage = `-- name: GetPage :one
SELECT id, title, handle, subtitle, description, stype, content, image, visibility, seo, meta, uts FROM pages WHERE id = $1
`

type GetPageRow struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Handle      string       `json:"handle"`
	Subtitle    string       `json:"subtitle"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Content     string       `json:"content"`
	Image       string       `json:"image"`
	Visibility  int16        `json:"visibility"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
	Uts         pgtype.Int8  `json:"uts"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Stype,
		&i.Content,
		&i.Image,
		&i.Visibility,
		&i.Seo,
		&i.Meta,
		&i.Uts,
	)
	return i, err
}

const switchPageStatus = `-- name: SwitchPageStatus :exec
UPDATE pages SET
    status = $1,
    uts = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $2
`

type SwitchPageStatusParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) SwitchPageStatus(ctx context.Context, arg SwitchPageStatusParams) error {
	_, err := q.db.Exec(ctx, switchPageStatus, arg.Status, arg.ID)
	return err
}

const switchPageVisibility = `-- name: SwitchPageVisibility :exec
UPDATE pages SET
    visibility = $1,
    uts = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $2
`

type SwitchPageVisibilityParams struct {
	Visibility int16 `json:"visibility"`
	ID         int64 `json:"id"`
}

func (q *Queries) SwitchPageVisibility(ctx context.Context, arg SwitchPageVisibilityParams) error {
	_, err := q.db.Exec(ctx, switchPageVisibility, arg.Visibility, arg.ID)
	return err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages SET
    title = $2, subtitle = $3, description = $4, stype = $5, content = $6, image = $7, visibility = $8, seo = $9, meta = $10
WHERE id = $1
`

type UpdatePageParams struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	Subtitle    string       `json:"subtitle"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Content     string       `json:"content"`
	Image       string       `json:"image"`
	Visibility  int16        `json:"visibility"`
	Seo         dbtypes.JSON `json:"seo"`
	Meta        dbtypes.JSON `json:"meta"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.Exec(ctx, updatePage,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Stype,
		arg.Content,
		arg.Image,
		arg.Visibility,
		arg.Seo,
		arg.Meta,
	)
	return err
}
