// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baseProductCountSql = `-- name: BaseProductCountSql :one
SELECT COUNT(*) FROM products
`

func (q *Queries) BaseProductCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseProductCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseProductListSql = `-- name: BaseProductListSql :many
SELECT id, name, handle, tags, status, deleted, sku_num, weight_g, brand, category, main_image, sales_count, stock, price, cts, uts FROM products
`

func (q *Queries) BaseProductListSql(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, baseProductListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Tags,
			&i.Status,
			&i.Deleted,
			&i.SkuNum,
			&i.WeightG,
			&i.Brand,
			&i.Category,
			&i.MainImage,
			&i.SalesCount,
			&i.Stock,
			&i.Price,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProductMain = `-- name: CreateProductMain :one
INSERT INTO products (
    id,
    name,
    handle,
    tags,
    weight_g,
    brand,
    category,
    main_image,
    price,
    sku_num,
    sales_count,
    stock
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id
`

type CreateProductMainParams struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Handle     string         `json:"handle"`
	Tags       []string       `json:"tags"`
	WeightG    int32          `json:"weight_g"`
	Brand      string         `json:"brand"`
	Category   string         `json:"category"`
	MainImage  string         `json:"main_image"`
	Price      pgtype.Numeric `json:"price"`
	SkuNum     int16          `json:"sku_num"`
	SalesCount int32          `json:"sales_count"`
	Stock      int32          `json:"stock"`
}

func (q *Queries) CreateProductMain(ctx context.Context, arg CreateProductMainParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProductMain,
		arg.ID,
		arg.Name,
		arg.Handle,
		arg.Tags,
		arg.WeightG,
		arg.Brand,
		arg.Category,
		arg.MainImage,
		arg.Price,
		arg.SkuNum,
		arg.SalesCount,
		arg.Stock,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, handle, tags, status, deleted, sku_num, weight_g, brand, category, main_image, sales_count, stock, price, cts, uts FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Tags,
		&i.Status,
		&i.Deleted,
		&i.SkuNum,
		&i.WeightG,
		&i.Brand,
		&i.Category,
		&i.MainImage,
		&i.SalesCount,
		&i.Stock,
		&i.Price,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const getProductCount = `-- name: GetProductCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductHandleCheck = `-- name: GetProductHandleCheck :one
SELECT COUNT(*) FROM products WHERE handle = $1
`

func (q *Queries) GetProductHandleCheck(ctx context.Context, handle string) (int64, error) {
	row := q.db.QueryRow(ctx, getProductHandleCheck, handle)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductHandleCount = `-- name: GetProductHandleCount :one
SELECT COUNT(*) FROM products WHERE handle LIKE $1 || '%'
`

func (q *Queries) GetProductHandleCount(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getProductHandleCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducts = `-- name: ListProducts :many
SELECT  id,name, handle, tags, weight_g,deleted,status, brand, category, main_image, price,sales_count,cts
FROM products
WHERE deleted = 0
ORDER BY uts desc
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Handle     string         `json:"handle"`
	Tags       []string       `json:"tags"`
	WeightG    int32          `json:"weight_g"`
	Deleted    int16          `json:"deleted"`
	Status     int16          `json:"status"`
	Brand      string         `json:"brand"`
	Category   string         `json:"category"`
	MainImage  string         `json:"main_image"`
	Price      pgtype.Numeric `json:"price"`
	SalesCount int32          `json:"sales_count"`
	Cts        pgtype.Int8    `json:"cts"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Tags,
			&i.WeightG,
			&i.Deleted,
			&i.Status,
			&i.Brand,
			&i.Category,
			&i.MainImage,
			&i.Price,
			&i.SalesCount,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductMain = `-- name: UpdateProductMain :exec
UPDATE products
SET
    name        = $2,
    tags        = $3,
    status      = $4,
    deleted     = $5,
    sku_num     = $6,
    weight_g    = $7,
    brand       = $8,
    category    = $9,
    main_image  = $10,
    sales_count = $11,
    stock       = $12,
    price       = $13
WHERE id = $1
`

type UpdateProductMainParams struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Tags       []string       `json:"tags"`
	Status     int16          `json:"status"`
	Deleted    int16          `json:"deleted"`
	SkuNum     int16          `json:"sku_num"`
	WeightG    int32          `json:"weight_g"`
	Brand      string         `json:"brand"`
	Category   string         `json:"category"`
	MainImage  string         `json:"main_image"`
	SalesCount int32          `json:"sales_count"`
	Stock      int32          `json:"stock"`
	Price      pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateProductMain(ctx context.Context, arg UpdateProductMainParams) error {
	_, err := q.db.Exec(ctx, updateProductMain,
		arg.ID,
		arg.Name,
		arg.Tags,
		arg.Status,
		arg.Deleted,
		arg.SkuNum,
		arg.WeightG,
		arg.Brand,
		arg.Category,
		arg.MainImage,
		arg.SalesCount,
		arg.Stock,
		arg.Price,
	)
	return err
}

const updateProductMainImage = `-- name: UpdateProductMainImage :exec
UPDATE products SET
    main_image = $1
WHERE id = $2
`

type UpdateProductMainImageParams struct {
	MainImage string `json:"main_image"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateProductMainImage(ctx context.Context, arg UpdateProductMainImageParams) error {
	_, err := q.db.Exec(ctx, updateProductMainImage, arg.MainImage, arg.ID)
	return err
}

const updateProductMainSkuNum = `-- name: UpdateProductMainSkuNum :exec
UPDATE products SET
    sku_num = $1
WHERE id = $2
`

type UpdateProductMainSkuNumParams struct {
	SkuNum int16 `json:"sku_num"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateProductMainSkuNum(ctx context.Context, arg UpdateProductMainSkuNumParams) error {
	_, err := q.db.Exec(ctx, updateProductMainSkuNum, arg.SkuNum, arg.ID)
	return err
}
