// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_options.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const createProductOptions = `-- name: CreateProductOptions :exec
INSERT INTO product_options (
    product_id,
    options
) VALUES (
    $1, $2
)
`

type CreateProductOptionsParams struct {
	ProductID int64        `json:"product_id"`
	Options   dbtypes.JSON `json:"options"`
}

func (q *Queries) CreateProductOptions(ctx context.Context, arg CreateProductOptionsParams) error {
	_, err := q.db.Exec(ctx, createProductOptions, arg.ProductID, arg.Options)
	return err
}

const getProductOptions = `-- name: GetProductOptions :one
SELECT options FROM product_options WHERE product_id = $1
`

func (q *Queries) GetProductOptions(ctx context.Context, productID int64) (dbtypes.JSON, error) {
	row := q.db.QueryRow(ctx, getProductOptions, productID)
	var options dbtypes.JSON
	err := row.Scan(&options)
	return options, err
}
