// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_skus.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProductSku = `-- name: CreateProductSku :exec
INSERT INTO product_skus (
    product_id,
    name,
    image,
    price,
    stock,
    weight_g,
    attrs,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateProductSkuParams struct {
	ProductID int64          `json:"product_id"`
	Name      string         `json:"name"`
	Image     string         `json:"image"`
	Price     pgtype.Numeric `json:"price"`
	Stock     int32          `json:"stock"`
	WeightG   int32          `json:"weight_g"`
	Attrs     dbtypes.JSON   `json:"attrs"`
	Status    int16          `json:"status"`
}

func (q *Queries) CreateProductSku(ctx context.Context, arg CreateProductSkuParams) error {
	_, err := q.db.Exec(ctx, createProductSku,
		arg.ProductID,
		arg.Name,
		arg.Image,
		arg.Price,
		arg.Stock,
		arg.WeightG,
		arg.Attrs,
		arg.Status,
	)
	return err
}

const getProductSkus = `-- name: GetProductSkus :many
SELECT id, product_id, name, image, price, stock, weight_g, attrs, status, cts, uts FROM product_skus WHERE product_id = $1
`

func (q *Queries) GetProductSkus(ctx context.Context, productID int64) ([]ProductSku, error) {
	rows, err := q.db.Query(ctx, getProductSkus, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSku
	for rows.Next() {
		var i ProductSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Image,
			&i.Price,
			&i.Stock,
			&i.WeightG,
			&i.Attrs,
			&i.Status,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
