// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_details.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const createProductDetails = `-- name: CreateProductDetails :exec
INSERT INTO product_details (
    product_id,
    images,
    videos,
    specs
) VALUES (
    $1, $2, $3, $4
)
`

type CreateProductDetailsParams struct {
	ProductID int64        `json:"product_id"`
	Images    []string     `json:"images"`
	Videos    []string     `json:"videos"`
	Specs     dbtypes.JSON `json:"specs"`
}

func (q *Queries) CreateProductDetails(ctx context.Context, arg CreateProductDetailsParams) error {
	_, err := q.db.Exec(ctx, createProductDetails,
		arg.ProductID,
		arg.Images,
		arg.Videos,
		arg.Specs,
	)
	return err
}

const fetchProductDetail = `-- name: FetchProductDetail :one
SELECT images,videos,specs FROM product_details WHERE product_id = $1
`

type FetchProductDetailRow struct {
	Images []string     `json:"images"`
	Videos []string     `json:"videos"`
	Specs  dbtypes.JSON `json:"specs"`
}

func (q *Queries) FetchProductDetail(ctx context.Context, productID int64) (FetchProductDetailRow, error) {
	row := q.db.QueryRow(ctx, fetchProductDetail, productID)
	var i FetchProductDetailRow
	err := row.Scan(&i.Images, &i.Videos, &i.Specs)
	return i, err
}

const getProductDetails = `-- name: GetProductDetails :one
SELECT images, videos, specs FROM product_details WHERE product_id = $1
`

type GetProductDetailsRow struct {
	Images []string     `json:"images"`
	Videos []string     `json:"videos"`
	Specs  dbtypes.JSON `json:"specs"`
}

func (q *Queries) GetProductDetails(ctx context.Context, productID int64) (GetProductDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProductDetails, productID)
	var i GetProductDetailsRow
	err := row.Scan(&i.Images, &i.Videos, &i.Specs)
	return i, err
}

const updateProductDetails = `-- name: UpdateProductDetails :exec
UPDATE product_details SET images = $2, videos = $3, specs = $4 WHERE product_id = $1
`

type UpdateProductDetailsParams struct {
	ProductID int64        `json:"product_id"`
	Images    []string     `json:"images"`
	Videos    []string     `json:"videos"`
	Specs     dbtypes.JSON `json:"specs"`
}

func (q *Queries) UpdateProductDetails(ctx context.Context, arg UpdateProductDetailsParams) error {
	_, err := q.db.Exec(ctx, updateProductDetails,
		arg.ProductID,
		arg.Images,
		arg.Videos,
		arg.Specs,
	)
	return err
}
