// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchDeleteCustomerReviews = `-- name: BatchDeleteCustomerReviews :exec
DELETE FROM product_customer_reviews WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteCustomerReviews(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteCustomerReviews, ids)
	return err
}

const batchDeleteReviews = `-- name: BatchDeleteReviews :exec
DELETE FROM product_reviews WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteReviews(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteReviews, ids)
	return err
}

const baseCustomerReviewsCountSql = `-- name: baseCustomerReviewsCountSql :one
SELECT
	count(*)
FROM product_customer_reviews
`

func (q *Queries) baseCustomerReviewsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseCustomerReviewsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseCustomerReviewsListSql = `-- name: baseCustomerReviewsListSql :many
SELECT
    id, product_id, user_name, user_avatar, title, content, rating, images, sort, status, cts
FROM product_customer_reviews
`

func (q *Queries) baseCustomerReviewsListSql(ctx context.Context) ([]ProductCustomerReview, error) {
	rows, err := q.db.Query(ctx, baseCustomerReviewsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCustomerReview
	for rows.Next() {
		var i ProductCustomerReview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserName,
			&i.UserAvatar,
			&i.Title,
			&i.Content,
			&i.Rating,
			&i.Images,
			&i.Sort,
			&i.Status,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const baseProductReviewsCountSql = `-- name: baseProductReviewsCountSql :one
SELECT
	count(*)
FROM products as p
`

func (q *Queries) baseProductReviewsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseProductReviewsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseProductReviewsListSql = `-- name: baseProductReviewsListSql :many
SELECT
    p.id,
    p.title,
    p.handle,
    p.main_image,
    r.rating,
    r.total,
    r.count,
    r.avg,
    r.status,
    r.cts
FROM products p
LEFT JOIN product_reviews r
    ON r.product_id = p.id
`

type baseProductReviewsListSqlRow struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Handle    string      `json:"handle"`
	MainImage string      `json:"main_image"`
	Rating    pgtype.Int2 `json:"rating"`
	Total     pgtype.Int2 `json:"total"`
	Count     pgtype.Int2 `json:"count"`
	Avg       pgtype.Int2 `json:"avg"`
	Status    pgtype.Int2 `json:"status"`
	Cts       pgtype.Int8 `json:"cts"`
}

func (q *Queries) baseProductReviewsListSql(ctx context.Context) ([]baseProductReviewsListSqlRow, error) {
	rows, err := q.db.Query(ctx, baseProductReviewsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []baseProductReviewsListSqlRow
	for rows.Next() {
		var i baseProductReviewsListSqlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.MainImage,
			&i.Rating,
			&i.Total,
			&i.Count,
			&i.Avg,
			&i.Status,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
