// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_skus.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const deleteProductSku = `-- name: DeleteProductSku :exec
DELETE FROM product_skus WHERE product_id = $1 and id = ANY($2::bigint[])
`

type DeleteProductSkuParams struct {
	ProductID int64   `json:"product_id"`
	Ids       []int64 `json:"ids"`
}

func (q *Queries) DeleteProductSku(ctx context.Context, arg DeleteProductSkuParams) error {
	_, err := q.db.Exec(ctx, deleteProductSku, arg.ProductID, arg.Ids)
	return err
}

const fetchProductSkus = `-- name: FetchProductSkus :many
SELECT id,product_id,title,image,price,attrs,akey FROM product_skus WHERE product_id = $1
`

type FetchProductSkusRow struct {
	ID        int64        `json:"id"`
	ProductID int64        `json:"product_id"`
	Title     string       `json:"title"`
	Image     string       `json:"image"`
	Price     int64        `json:"price"`
	Attrs     dbtypes.JSON `json:"attrs"`
	Akey      string       `json:"akey"`
}

func (q *Queries) FetchProductSkus(ctx context.Context, productID int64) ([]FetchProductSkusRow, error) {
	rows, err := q.db.Query(ctx, fetchProductSkus, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchProductSkusRow
	for rows.Next() {
		var i FetchProductSkusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Image,
			&i.Price,
			&i.Attrs,
			&i.Akey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductSkus = `-- name: GetProductSkus :many
SELECT id, product_id, title, code, image, price, stock, weight_g, status, stored, ukey, akey, attrs, cts, uts FROM product_skus WHERE product_id = $1
`

func (q *Queries) GetProductSkus(ctx context.Context, productID int64) ([]ProductSku, error) {
	rows, err := q.db.Query(ctx, getProductSkus, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSku
	for rows.Next() {
		var i ProductSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Code,
			&i.Image,
			&i.Price,
			&i.Stock,
			&i.WeightG,
			&i.Status,
			&i.Stored,
			&i.Ukey,
			&i.Akey,
			&i.Attrs,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSkuStored = `-- name: UpdateProductSkuStored :exec
UPDATE product_skus SET stored = 1 WHERE product_id = $1
`

func (q *Queries) UpdateProductSkuStored(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, updateProductSkuStored, productID)
	return err
}
