// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baseProductReviewsCountSql = `-- name: baseProductReviewsCountSql :one
SELECT
	count(*)
FROM products as p
`

func (q *Queries) baseProductReviewsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseProductReviewsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseProductReviewsListSql = `-- name: baseProductReviewsListSql :many
SELECT
    p.id,
    p.title,
    p.handle,
    p.main_image,
    r.rating,
    r.total,
    r.count,
    r.avg,
    r.status,
    r.cts
FROM products p
LEFT JOIN product_reviews r
    ON r.product_id = p.id
`

type baseProductReviewsListSqlRow struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Handle    string      `json:"handle"`
	MainImage string      `json:"main_image"`
	Rating    pgtype.Int2 `json:"rating"`
	Total     pgtype.Int2 `json:"total"`
	Count     pgtype.Int2 `json:"count"`
	Avg       pgtype.Int2 `json:"avg"`
	Status    pgtype.Int2 `json:"status"`
	Cts       pgtype.Int8 `json:"cts"`
}

func (q *Queries) baseProductReviewsListSql(ctx context.Context) ([]baseProductReviewsListSqlRow, error) {
	rows, err := q.db.Query(ctx, baseProductReviewsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []baseProductReviewsListSqlRow
	for rows.Next() {
		var i baseProductReviewsListSqlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.MainImage,
			&i.Rating,
			&i.Total,
			&i.Count,
			&i.Avg,
			&i.Status,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
