// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_content.sql

package db

import (
	"context"
)

const createProductContent = `-- name: CreateProductContent :exec
INSERT INTO product_content (
    product_id,
    content
) VALUES (
    $1, $2
)
`

type CreateProductContentParams struct {
	ProductID int64  `json:"product_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateProductContent(ctx context.Context, arg CreateProductContentParams) error {
	_, err := q.db.Exec(ctx, createProductContent, arg.ProductID, arg.Content)
	return err
}

const getProductContent = `-- name: GetProductContent :one
SELECT content FROM product_content WHERE product_id = $1
`

func (q *Queries) GetProductContent(ctx context.Context, productID int64) (string, error) {
	row := q.db.QueryRow(ctx, getProductContent, productID)
	var content string
	err := row.Scan(&content)
	return content, err
}

const updateProductContent = `-- name: UpdateProductContent :exec
UPDATE product_content SET content = $2 WHERE product_id = $1
`

type UpdateProductContentParams struct {
	ProductID int64  `json:"product_id"`
	Content   string `json:"content"`
}

func (q *Queries) UpdateProductContent(ctx context.Context, arg UpdateProductContentParams) error {
	_, err := q.db.Exec(ctx, updateProductContent, arg.ProductID, arg.Content)
	return err
}
