// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const baseProductReviewsCountSql = `-- name: baseProductReviewsCountSql :one
SELECT
	count(*)
FROM products p
JOIN product_reviews c 
    ON c.product_id = p.id
`

func (q *Queries) baseProductReviewsCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseProductReviewsCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseProductReviewsListSql = `-- name: baseProductReviewsListSql :many
SELECT
    p.id,
    p.name,
    p.handle,
    p.main_image,
    c.rating,
    c.total,
    c.count,
    c.avg,
    c.status,
    c.cts
FROM products p
JOIN product_reviews c 
    ON c.product_id = p.id
`

type baseProductReviewsListSqlRow struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Handle    string      `json:"handle"`
	MainImage string      `json:"main_image"`
	Rating    int16       `json:"rating"`
	Total     int16       `json:"total"`
	Count     int16       `json:"count"`
	Avg       int16       `json:"avg"`
	Status    int16       `json:"status"`
	Cts       pgtype.Int8 `json:"cts"`
}

func (q *Queries) baseProductReviewsListSql(ctx context.Context) ([]baseProductReviewsListSqlRow, error) {
	rows, err := q.db.Query(ctx, baseProductReviewsListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []baseProductReviewsListSqlRow
	for rows.Next() {
		var i baseProductReviewsListSqlRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.MainImage,
			&i.Rating,
			&i.Total,
			&i.Count,
			&i.Avg,
			&i.Status,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
