// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

const baseProductCountSql = `-- name: BaseProductCountSql :one
SELECT COUNT(*) FROM products
`

func (q *Queries) BaseProductCountSql(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, baseProductCountSql)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const baseProductListSql = `-- name: BaseProductListSql :many
SELECT id, title, handle, subtitle, description, tags, status, price, sid, deleted, sku_num, weight_g, brand, category, main_image, sales_count, points, stock, cts, uts FROM products
`

func (q *Queries) BaseProductListSql(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, baseProductListSql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Tags,
			&i.Status,
			&i.Price,
			&i.Sid,
			&i.Deleted,
			&i.SkuNum,
			&i.WeightG,
			&i.Brand,
			&i.Category,
			&i.MainImage,
			&i.SalesCount,
			&i.Points,
			&i.Stock,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchDeleteProducts = `-- name: BatchDeleteProducts :exec
DELETE FROM products WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteProducts(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteProducts, ids)
	return err
}

const bindProductToSite = `-- name: BindProductToSite :exec
UPDATE products SET
    sid = $1
WHERE id = ANY($2::bigint[])
`

type BindProductToSiteParams struct {
	Sid int64   `json:"sid"`
	Ids []int64 `json:"ids"`
}

func (q *Queries) BindProductToSite(ctx context.Context, arg BindProductToSiteParams) error {
	_, err := q.db.Exec(ctx, bindProductToSite, arg.Sid, arg.Ids)
	return err
}

const createProductMain = `-- name: CreateProductMain :one
INSERT INTO products (
    id,
    title,
    subtitle,
    handle,
    tags,
    weight_g,
    brand,
    category,
    main_image,
    description,
    price,
    sku_num,    
    sales_count,
    stock,
    points
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13 , $14, $15
)
RETURNING id
`

type CreateProductMainParams struct {
	ID          int64    `json:"id"`
	Title       string   `json:"title"`
	Subtitle    string   `json:"subtitle"`
	Handle      string   `json:"handle"`
	Tags        []string `json:"tags"`
	WeightG     int32    `json:"weight_g"`
	Brand       string   `json:"brand"`
	Category    string   `json:"category"`
	MainImage   string   `json:"main_image"`
	Description string   `json:"description"`
	Price       int64    `json:"price"`
	SkuNum      int16    `json:"sku_num"`
	SalesCount  int32    `json:"sales_count"`
	Stock       int32    `json:"stock"`
	Points      int32    `json:"points"`
}

func (q *Queries) CreateProductMain(ctx context.Context, arg CreateProductMainParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProductMain,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Handle,
		arg.Tags,
		arg.WeightG,
		arg.Brand,
		arg.Category,
		arg.MainImage,
		arg.Description,
		arg.Price,
		arg.SkuNum,
		arg.SalesCount,
		arg.Stock,
		arg.Points,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const fetchProductById = `-- name: FetchProductById :one
SELECT id,title,handle,main_image,tags,subtitle,sales_count,price,stock,points 
FROM products WHERE deleted = 0 AND status = 0 AND sid IN (0::bigint,$2) AND id = $1
`

type FetchProductByIdParams struct {
	ID  int64 `json:"id"`
	Sid int64 `json:"sid"`
}

type FetchProductByIdRow struct {
	ID         int64    `json:"id"`
	Title      string   `json:"title"`
	Handle     string   `json:"handle"`
	MainImage  string   `json:"main_image"`
	Tags       []string `json:"tags"`
	Subtitle   string   `json:"subtitle"`
	SalesCount int32    `json:"sales_count"`
	Price      int64    `json:"price"`
	Stock      int32    `json:"stock"`
	Points     int32    `json:"points"`
}

func (q *Queries) FetchProductById(ctx context.Context, arg FetchProductByIdParams) (FetchProductByIdRow, error) {
	row := q.db.QueryRow(ctx, fetchProductById, arg.ID, arg.Sid)
	var i FetchProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.MainImage,
		&i.Tags,
		&i.Subtitle,
		&i.SalesCount,
		&i.Price,
		&i.Stock,
		&i.Points,
	)
	return i, err
}

const fetchProductList = `-- name: FetchProductList :many
SELECT title,handle,main_image,tags,sales_count,price,stock,points FROM products WHERE sid IN (0::bigint,$1) ORDER BY uts DESC LIMIT $2 OFFSET $3
`

type FetchProductListParams struct {
	Sid    int64 `json:"sid"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FetchProductListRow struct {
	Title      string   `json:"title"`
	Handle     string   `json:"handle"`
	MainImage  string   `json:"main_image"`
	Tags       []string `json:"tags"`
	SalesCount int32    `json:"sales_count"`
	Price      int64    `json:"price"`
	Stock      int32    `json:"stock"`
	Points     int32    `json:"points"`
}

func (q *Queries) FetchProductList(ctx context.Context, arg FetchProductListParams) ([]FetchProductListRow, error) {
	fmt.Println(fetchProductList, arg.Sid, arg.Limit, arg.Offset)
	rows, err := q.db.Query(ctx, fetchProductList, arg.Sid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchProductListRow
	for rows.Next() {
		var i FetchProductListRow
		if err := rows.Scan(
			&i.Title,
			&i.Handle,
			&i.MainImage,
			&i.Tags,
			&i.SalesCount,
			&i.Price,
			&i.Stock,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, title, handle, subtitle, description, tags, status, price, sid, deleted, sku_num, weight_g, brand, category, main_image, sales_count, points, stock, cts, uts FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Tags,
		&i.Status,
		&i.Price,
		&i.Sid,
		&i.Deleted,
		&i.SkuNum,
		&i.WeightG,
		&i.Brand,
		&i.Category,
		&i.MainImage,
		&i.SalesCount,
		&i.Points,
		&i.Stock,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const getProductCount = `-- name: GetProductCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductHandleCheck = `-- name: GetProductHandleCheck :one
SELECT COUNT(*) FROM products WHERE handle = $1
`

func (q *Queries) GetProductHandleCheck(ctx context.Context, handle string) (int64, error) {
	row := q.db.QueryRow(ctx, getProductHandleCheck, handle)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductHandleCount = `-- name: GetProductHandleCount :one
SELECT COUNT(*) FROM products WHERE handle LIKE $1 || '%'
`

func (q *Queries) GetProductHandleCount(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getProductHandleCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducts = `-- name: ListProducts :many
SELECT  id,title, handle, tags, weight_g,deleted,status, brand, category, main_image, price,sales_count,points,cts
FROM products
WHERE deleted = 0
ORDER BY uts desc
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID         int64       `json:"id"`
	Title      string      `json:"title"`
	Handle     string      `json:"handle"`
	Tags       []string    `json:"tags"`
	WeightG    int32       `json:"weight_g"`
	Deleted    int16       `json:"deleted"`
	Status     int16       `json:"status"`
	Brand      string      `json:"brand"`
	Category   string      `json:"category"`
	MainImage  string      `json:"main_image"`
	Price      int64       `json:"price"`
	SalesCount int32       `json:"sales_count"`
	Points     int32       `json:"points"`
	Cts        pgtype.Int8 `json:"cts"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Tags,
			&i.WeightG,
			&i.Deleted,
			&i.Status,
			&i.Brand,
			&i.Category,
			&i.MainImage,
			&i.Price,
			&i.SalesCount,
			&i.Points,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductMain = `-- name: UpdateProductMain :exec
UPDATE products
SET
    title       = $2,
    tags        = $3,
    status      = $4,
    deleted     = $5,
    sku_num     = $6,
    weight_g    = $7,
    brand       = $8,
    category    = $9,
    main_image  = $10,
    sales_count = $11,
    stock       = $12,
    price       = $13,
    points      = $14,
    subtitle    = $15,
    description = $16
WHERE id = $1
`

type UpdateProductMainParams struct {
	ID          int64    `json:"id"`
	Title       string   `json:"title"`
	Tags        []string `json:"tags"`
	Status      int16    `json:"status"`
	Deleted     int16    `json:"deleted"`
	SkuNum      int16    `json:"sku_num"`
	WeightG     int32    `json:"weight_g"`
	Brand       string   `json:"brand"`
	Category    string   `json:"category"`
	MainImage   string   `json:"main_image"`
	SalesCount  int32    `json:"sales_count"`
	Stock       int32    `json:"stock"`
	Price       int64    `json:"price"`
	Points      int32    `json:"points"`
	Subtitle    string   `json:"subtitle"`
	Description string   `json:"description"`
}

func (q *Queries) UpdateProductMain(ctx context.Context, arg UpdateProductMainParams) error {
	_, err := q.db.Exec(ctx, updateProductMain,
		arg.ID,
		arg.Title,
		arg.Tags,
		arg.Status,
		arg.Deleted,
		arg.SkuNum,
		arg.WeightG,
		arg.Brand,
		arg.Category,
		arg.MainImage,
		arg.SalesCount,
		arg.Stock,
		arg.Price,
		arg.Points,
		arg.Subtitle,
		arg.Description,
	)
	return err
}

const updateProductMainImage = `-- name: UpdateProductMainImage :exec
UPDATE products SET
    main_image = $1
WHERE id = $2 AND main_image = ''
`

type UpdateProductMainImageParams struct {
	MainImage string `json:"main_image"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateProductMainImage(ctx context.Context, arg UpdateProductMainImageParams) error {
	_, err := q.db.Exec(ctx, updateProductMainImage, arg.MainImage, arg.ID)
	return err
}

const updateProductMainSkuNum = `-- name: UpdateProductMainSkuNum :exec
UPDATE products SET
    sku_num = $1
WHERE id = $2
`

type UpdateProductMainSkuNumParams struct {
	SkuNum int16 `json:"sku_num"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateProductMainSkuNum(ctx context.Context, arg UpdateProductMainSkuNumParams) error {
	_, err := q.db.Exec(ctx, updateProductMainSkuNum, arg.SkuNum, arg.ID)
	return err
}

const updateProductStatus = `-- name: UpdateProductStatus :exec
UPDATE products SET
    status = $2
WHERE id = $1
`

type UpdateProductStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) error {
	_, err := q.db.Exec(ctx, updateProductStatus, arg.ID, arg.Status)
	return err
}
