// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_sku_json.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const createProductSkuJson = `-- name: CreateProductSkuJson :exec
INSERT INTO product_sku_json (
    product_id,
    skus
) VALUES (
    $1, $2
)
`

type CreateProductSkuJsonParams struct {
	ProductID int64        `json:"product_id"`
	Skus      dbtypes.JSON `json:"skus"`
}

func (q *Queries) CreateProductSkuJson(ctx context.Context, arg CreateProductSkuJsonParams) error {
	_, err := q.db.Exec(ctx, createProductSkuJson, arg.ProductID, arg.Skus)
	return err
}

const updateProductSkuJson = `-- name: UpdateProductSkuJson :exec
UPDATE product_sku_json SET skus = $2 WHERE product_id = $1
`

type UpdateProductSkuJsonParams struct {
	ProductID int64        `json:"product_id"`
	Skus      dbtypes.JSON `json:"skus"`
}

func (q *Queries) UpdateProductSkuJson(ctx context.Context, arg UpdateProductSkuJsonParams) error {
	_, err := q.db.Exec(ctx, updateProductSkuJson, arg.ProductID, arg.Skus)
	return err
}
