// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, handle, tags, weight_g, brand, category, main_image_url, price,sales_count
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, handle, tags, status, deleted, weight_g, brand, category, main_image_url, sales_count, price, cts, uts
`

type CreateProductParams struct {
	Name         string         `json:"name"`
	Handle       string         `json:"handle"`
	Tags         []string       `json:"tags"`
	WeightG      pgtype.Int4    `json:"weight_g"`
	Brand        pgtype.Text    `json:"brand"`
	Category     pgtype.Text    `json:"category"`
	MainImageUrl pgtype.Text    `json:"main_image_url"`
	Price        pgtype.Numeric `json:"price"`
	SalesCount   pgtype.Int4    `json:"sales_count"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Handle,
		arg.Tags,
		arg.WeightG,
		arg.Brand,
		arg.Category,
		arg.MainImageUrl,
		arg.Price,
		arg.SalesCount,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Tags,
		&i.Status,
		&i.Deleted,
		&i.WeightG,
		&i.Brand,
		&i.Category,
		&i.MainImageUrl,
		&i.SalesCount,
		&i.Price,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, handle, tags, status, deleted, weight_g, brand, category, main_image_url, sales_count, price, cts, uts FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Tags,
		&i.Status,
		&i.Deleted,
		&i.WeightG,
		&i.Brand,
		&i.Category,
		&i.MainImageUrl,
		&i.SalesCount,
		&i.Price,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const getProductCount = `-- name: GetProductCount :one
SELECT COUNT(*) FROM products
`

func (q *Queries) GetProductCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducts = `-- name: ListProducts :many
SELECT  id,name, handle, tags, weight_g,deleted,status, brand, category, main_image_url, price,sales_count,cts
FROM products
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Handle       string         `json:"handle"`
	Tags         []string       `json:"tags"`
	WeightG      pgtype.Int4    `json:"weight_g"`
	Deleted      pgtype.Int2    `json:"deleted"`
	Status       pgtype.Int2    `json:"status"`
	Brand        pgtype.Text    `json:"brand"`
	Category     pgtype.Text    `json:"category"`
	MainImageUrl pgtype.Text    `json:"main_image_url"`
	Price        pgtype.Numeric `json:"price"`
	SalesCount   pgtype.Int4    `json:"sales_count"`
	Cts          pgtype.Int8    `json:"cts"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handle,
			&i.Tags,
			&i.WeightG,
			&i.Deleted,
			&i.Status,
			&i.Brand,
			&i.Category,
			&i.MainImageUrl,
			&i.Price,
			&i.SalesCount,
			&i.Cts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
