// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const createSite = `-- name: CreateSite :exec
INSERT INTO sites (
    id,
    name,
    domain,
    stype,
    site,
    config
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSiteParams struct {
	ID     int64        `json:"id"`
	Name   string       `json:"name"`
	Domain string       `json:"domain"`
	Stype  string       `json:"stype"`
	Site   dbtypes.JSON `json:"site"`
	Config dbtypes.JSON `json:"config"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) error {
	_, err := q.db.Exec(ctx, createSite,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Stype,
		arg.Site,
		arg.Config,
	)
	return err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const fetchSite = `-- name: FetchSite :one
SELECT site,config FROM sites WHERE id = $1
`

type FetchSiteRow struct {
	Site   dbtypes.JSON `json:"site"`
	Config dbtypes.JSON `json:"config"`
}

func (q *Queries) FetchSite(ctx context.Context, id int64) (FetchSiteRow, error) {
	row := q.db.QueryRow(ctx, fetchSite, id)
	var i FetchSiteRow
	err := row.Scan(&i.Site, &i.Config)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, name, domain, stype, site, config, cts, uts FROM sites WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Stype,
		&i.Site,
		&i.Config,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const siteList = `-- name: SiteList :many
SELECT id, name, domain, stype, site, config, cts, uts FROM sites
`

func (q *Queries) SiteList(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, siteList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Stype,
			&i.Site,
			&i.Config,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    name = $2,
    domain = $3,
    stype = $4,
    site = $5,
    config = $6,
    uts = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $1
`

type UpdateSiteParams struct {
	ID     int64        `json:"id"`
	Name   string       `json:"name"`
	Domain string       `json:"domain"`
	Stype  string       `json:"stype"`
	Site   dbtypes.JSON `json:"site"`
	Config dbtypes.JSON `json:"config"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.Exec(ctx, updateSite,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Stype,
		arg.Site,
		arg.Config,
	)
	return err
}
