// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"

	"github.com/cms/dbtypes"
)

const batchDeleteSites = `-- name: BatchDeleteSites :exec
DELETE FROM sites WHERE id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteSites(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, batchDeleteSites, ids)
	return err
}

const createSite = `-- name: CreateSite :exec
INSERT INTO sites (
    id,
    name,
    image,
    description,
    domain,
    stype,
    meta,
    config
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSiteParams struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	Domain      string       `json:"domain"`
	Stype       string       `json:"stype"`
	Meta        dbtypes.JSON `json:"meta"`
	Config      dbtypes.JSON `json:"config"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) error {
	_, err := q.db.Exec(ctx, createSite,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.Description,
		arg.Domain,
		arg.Stype,
		arg.Meta,
		arg.Config,
	)
	return err
}

const fetchSite = `-- name: FetchSite :one
SELECT name,domain,image,description,meta,config FROM sites WHERE id = $1
`

type FetchSiteRow struct {
	Name        string       `json:"name"`
	Domain      string       `json:"domain"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	Meta        dbtypes.JSON `json:"meta"`
	Config      dbtypes.JSON `json:"config"`
}

func (q *Queries) FetchSite(ctx context.Context, id int64) (FetchSiteRow, error) {
	row := q.db.QueryRow(ctx, fetchSite, id)
	var i FetchSiteRow
	err := row.Scan(
		&i.Name,
		&i.Domain,
		&i.Image,
		&i.Description,
		&i.Meta,
		&i.Config,
	)
	return i, err
}

const getDomains = `-- name: GetDomains :many
SELECT id,domain FROM sites WHERE status = 0
`

type GetDomainsRow struct {
	ID     int64  `json:"id"`
	Domain string `json:"domain"`
}

func (q *Queries) GetDomains(ctx context.Context) ([]GetDomainsRow, error) {
	rows, err := q.db.Query(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDomainsRow
	for rows.Next() {
		var i GetDomainsRow
		if err := rows.Scan(&i.ID, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSite = `-- name: GetSite :one
SELECT id, name, domain, image, description, status, stype, meta, config, cts, uts FROM sites WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Image,
		&i.Description,
		&i.Status,
		&i.Stype,
		&i.Meta,
		&i.Config,
		&i.Cts,
		&i.Uts,
	)
	return i, err
}

const siteList = `-- name: SiteList :many
SELECT id, name, domain, image, description, status, stype, meta, config, cts, uts FROM sites ORDER BY uts DESC
`

func (q *Queries) SiteList(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, siteList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Image,
			&i.Description,
			&i.Status,
			&i.Stype,
			&i.Meta,
			&i.Config,
			&i.Cts,
			&i.Uts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const switchSiteStatus = `-- name: SwitchSiteStatus :exec
UPDATE sites SET
    status = $1,
    uts = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $2
`

type SwitchSiteStatusParams struct {
	Status int16 `json:"status"`
	ID     int64 `json:"id"`
}

func (q *Queries) SwitchSiteStatus(ctx context.Context, arg SwitchSiteStatusParams) error {
	_, err := q.db.Exec(ctx, switchSiteStatus, arg.Status, arg.ID)
	return err
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    name = $1,
    image = $2,
    description = $3,
    stype = $4,
    meta = $5,
    config = $6,
    domain = $7,
    uts = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $8
`

type UpdateSiteParams struct {
	Name        string       `json:"name"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	Stype       string       `json:"stype"`
	Meta        dbtypes.JSON `json:"meta"`
	Config      dbtypes.JSON `json:"config"`
	Domain      string       `json:"domain"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.Exec(ctx, updateSite,
		arg.Name,
		arg.Image,
		arg.Description,
		arg.Stype,
		arg.Meta,
		arg.Config,
		arg.Domain,
		arg.ID,
	)
	return err
}
