// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"
)

const updateProductSite = `-- name: UpdateProductSite :exec
UPDATE products SET sid = $2 WHERE sid = $1
`

type UpdateProductSiteParams struct {
	Sid   int64 `json:"sid"`
	Sid_2 int64 `json:"sid_2"`
}

func (q *Queries) UpdateProductSite(ctx context.Context, arg UpdateProductSiteParams) error {
	_, err := q.db.Exec(ctx, updateProductSite, arg.Sid, arg.Sid_2)
	return err
}
